### ISSUE TITLE
Extendscript es5shim

### ISSUE THREAD

**Issue by ff6347** [ExtendScript/AMA#11]
I've been thinking about creating a new repo for es5shims and would like to know who else is collecting es5shims

@EugenTepin is https://github.com/EugenTepin/ps-scripting-es5shim

@fabianmoronzirfas is https://github.com/fabianmoronzirfas/extendscript.prototypes

Who else does it?

Also there is the need for a good descriptive name.

**Comment by fabianmoronzirfas** [comment]
Name suggestion: extendscript-es5-shim

**Comment by fabianmoronzirfas** [comment]
@BenGaumond does it https://github.com/BenGaumond/after-effects/blob/master/lib/includes/es5-shim.jsx
