### ISSUE TITLE
JSX Syntax Highlighting on GitHub

### ISSUE THREAD

**Issue by indiscripts** [ExtendScript/AMA#12]
Hi colleagues,

As you may know I've released on GH the alpha release of an InDesign/ExtendScript framework—called IdExtenso—and I'm facing a cosmetic problem: the syntax highlighter (`linguist`?) does not properly address the JSX language in all its specific features.

My main issue is about the triple quote syntax (allowed in literal strings.) Here is an example of a code being wrongly parsed as faulty: [IdExtenso/$$.jsxinc](https://github.com/indiscripts/IdExtenso/blob/master/%24%24.jsxinc)

Does any of you know a workaround or some hidden option to make JSX fully recognized and highlighted here?

Thanks a lot for any hint.

Best,
Marc

**Comment by fabianmoronzirfas** [comment]
I don't think you can change the GH syntax highlighting. Might a thing to ask the GitHub support. Big problem is also that Facebook didn't care about Adobes jsx extension. So even if there is some way to do tings like these, how to decide if it is react jsx or Adobe jsx.

**Comment by indiscripts** [comment]
Hi Fabian,

Thanks for your feedback.

The good news is, by contrast with JavaScript, react/JSX (aka `linguist-language=JSX`) seems syntactically closer to Adobe/JSX. (?)

Not tested in depth, but for the time being

    *.jsx* linguist-language=JSX

sounds like a better directive in my `.gitattributes`, in terms of syntax highlighting.

However, the `'''triple quote syntax'''` problem remains visible in important areas of the code. I found that the CSS `class="pl-ii"` is responsible for the RED ZONE artifact. Looking for a way to inhibit it…

**Comment by indiscripts** [comment]
(…)

Anyway, I agree, we should tell to `linguist` contributors that there is another JSX than Babel's one!
See [linguist JSX](https://github.com/github/linguist/tree/master/samples/JSX)

Best,
Marc

**Comment by fabianmoronzirfas** [comment]
> Anyway, I agree, we should tell to linguist contributors that there is another JSX than Babel's one!

This would be great.
