### ISSUE TITLE
Need some help bringing barcodes to ExtendScript

### ISSUE THREAD

**Issue by duckrabbitstudio** [ExtendScript/AMA#13]
Disclaimer: I'm a Graphic Designer/scripter with quite some experience scripting in ExtendScript for InDesign and PhotoShop

I'm trying to implement the [Barcode Writer in Pure JavaScript](https://github.com/metafloor/bwip-js) in an ExtendsScript environment, so I could use the "encoding" part, and generate the barcodes themselves in Vector format in the Adobe Apps themselves.

This way the final barcodes are always High Res/scalable, and will print fine, and quite a few people will be able to automate complex workflows through datamerge & scripting. (sticker printing etc…)

My main aim is to do this in a way it can be implemented in nearly the same way in PS, AI and ID, through a UI or through analysis of script labels, text fields etc… 

BWIPP (PostScript=the original)/BWIPJS  is the only encoder that has such a wide array of encodings and is exactly what I needed. (need GS1-128, DataBar Stacked, EAN-13, etc…)

But… the code uses UInt8Arrays and whatnot, in a more recent version of ECMAScript, and I'm quite [stuck](https://github.com/metafloor/bwip-js/issues/76), as ExtendScript remained in the 1990's

Polyfills don't seem to do what I need them to do, and always bring up new dependencies… They are also often offered with limited documentation, so after a while I don't know if they fail because of an overlooked issue or my own limited understanding of how to get this to work.

Is there a way out, or a more easily ported Barcode encoder? I can handle the UI/Data Gathering/Script Label and the Rendering stuff just fine, it's only the encoding I'm after…

**Comment by fabianmoronzirfas** [comment]
Have tried to use a CEP panel and have the code generation there and only pass something that Extendscript can handle over?

I recently collected some links on CEP Panels

CEP Reosources:   



- [Getting started with HTML5 (CEP) Panels for After Effects | Victoria Nece](http://victorianece.com/2015/12/getting-started-with-html5-cep-panels-for-after-effects/)
- [CEP | Victoria Nece](http://victorianece.com/tag/cep/)
- [Creative Cloud Extension SDK - CC extension resources | Adobe I/O](https://www.adobe.io/apis/creativecloud/cep.html)
- [CEP 5 Super mega guide: Extending Adobe apps with HTML5+Node.js | aphall.com](http://aphall.com/2014/08/cep-mega-guide-en/)
- [Adobe CEP](https://github.com/Adobe-CEP)
- [A Short Guide to HTML5 Extensions | Adobe Developer Connection](http://www.adobe.com/devnet/creativesuite/articles/a-short-guide-to-HTML5-extensions.html)
- [A Short Guide to HTML5 Extensions | Adobe Developer Connection](http://www.adobe.com/devnet/creativesuite/articles/a-short-guide-to-HTML5-extensions.html)
- [After Effects CC 2015 Panel SDK | Adobe Developer Connection](http://www.adobe.com/devnet/aftereffects/panelsdk/cc2015.html)
- [HTML5 (CEP) Panels for After Effects: Fixes, hacks and workarounds | Victoria Nece](http://victorianece.com/2015/12/html5-cep-panels-for-after-effects-fixes-hacks-and-workarounds/)
- [jenstroeger/Bookalope-CEP: Adobe CEP extension for InDesign to use the Bookalope cloud services.](https://github.com/jenstroeger/Bookalope-CEP)
- [Trevor-/CSTK: Adobe HTML extension Console for js, jsx and shell and extensions development help](https://github.com/Trevor-/CSTK)

**Comment by duckrabbitstudio** [comment]
Didn't know of these CEP panels… Thx! :-))
