### ISSUE TITLE
Select a specific layer in the timeline panel with ExtendScript

### ISSUE THREAD

**Issue by rudylee** [ExtendScript/AMA#14]
Hi,

Does anyone know how to select a specific layer in the timeline panel after opening the root comp in the viewer ?

I am trying to write a script to cut and paste layers in the timeline panel. See below:

![select layer](https://user-images.githubusercontent.com/191448/33545500-85f666fa-d932-11e7-9a36-c4e773d4888a.png)

This is the code that I have so far

```
pal.group1.debugBtn.onClick = function ()
{
    var file = importFile()

    var layer = file.layer(2)

    app.project.showWindow(true);

    file.openInViewer()

    layer.selected = true // This only select the layer in the project folder

    app.executeCommand(18)
};
```

Thanks

**Comment by rudylee** [comment]
Found the answer, I need to use `activeItem` because when you open a comp in the viewer, it becomes an `activeItem`

```
// deselect all layers in the active comp -- just in case
for (var i = 1; i <= app.project.activeItem.numLayers; i++) {
    app.project.activeItem.layer(i).selected = false;
}

// select the third layer of the active comp
app.project.activeItem.layer(3).selected = true;
```

**Comment by fabianmoronzirfas** [comment]
Awesome. 👍
