### ISSUE TITLE
add drop shadow to text layer in After Effects

### ISSUE THREAD

**Issue by marksantos22** [ExtendScript/AMA#16]
hi, is it possible to add drop shadow to a text layer via extendscript?.
if its possible can you provide some examples?
tnx in advance

**Comment by fabianmoronzirfas** [comment]
Hi @marksantos22   Which platform? ID AI PS AE PP…?

**Comment by marksantos22** [comment]
sorry i forgot, im using AE

**Comment by fabianmoronzirfas** [comment]
Hm. Wired. Seems like it is not possible directly in AE for layer styles.
You can add a dropShadow effect like this.

```js
function func() {
  app.beginUndoGroup("XXX");
  var curComp = app.project.activeItem;
  if (!curComp || !(curComp instanceof CompItem)) {
    alert("noComp");
    return;
  }

  var txt = curComp.layers.addText('foo');
 txt.Effects.addProperty("Drop Shadow");

  app.endUndoGroup();
}

func()

``` 

To enable layer styles people are using a workaround by using 

```js
app.executeCommand(app.findMenuCommandId("NAME OF YOUR MENU COMMAND IN YOUR LANGUAGE HERE")); // also takes a number associated with the command
```

See [this thead on creative cow](https://forums.creativecow.net/docs/forums/post.php?forumid=227&postid=19122&univpostid=19122&pview=t)
