### ISSUE TITLE
boilerplate project

### ISSUE THREAD

**Issue by ff6347** [ExtendScript/AMA#6]

**Comment by fabiantheblind** [comment]
boilerplates should be:  

- one repo per platform (AI, AE, PS, ID)
- tbd

**Comment by GitBruno** [comment]
Excuse my ignorance but why do we need seperate boilerplates for AI, AE, PS, ID?

**Comment by fabianmoronzirfas** [comment]
As you can see the idea is from mid 2016. I can't remember why we thought this is the way to go. :-)

**Comment by fabianmoronzirfas** [comment]
Maybe we close this one.
