### ISSUE TITLE
Changelog of Extendscript changes since AE CS6 Scripting Guide

### ISSUE THREAD

**Issue by michamedia** [ExtendScript/AMA#8]

**Comment by fabiantheblind** [comment]
@michamedia Yes this could be something to work on. What would be a could resource to extract that info from? And do you want to join and take this on? If so you can accept or decline your invite here https://github.com/ExtendScript

**Comment by michamedia** [comment]
@fabiantheblind yes I want to contribute to this org and accepted the invitation. The [blog posts](https://blogs.adobe.com/creativecloud/category/after-effects/) of the adobe AE team provide some information about the changes but aren't very nice to overview. So I would collect them in this repository and rearange/prepare them for other people. Other ressources are maybe the common forums like creative cow, aenhancer etc.

**Comment by fabiantheblind** [comment]
awesome lets create a repo for this. --> https://github.com/ExtendScript/changelog  

Best would be to write it in Markdown first. Maybe we convert it later on to a microsite using jekyll or what not

**Comment by wridgers** [comment]
I think a changelog would be good, but I do not think we need another repository to track this. There are already far too many repos. It's difficult to know what to post where (in fact, I don't know where to raise this issue - I'm just going to hijack this thread...)

I think a better approach would be to create a github pages static site. We can put things like the changelog, awesome lists, code of conduct, etc, there.

**Comment by fabiantheblind** [comment]
> There are already far too many repos. It's difficult to know what to post where (in fact, I don't know where to raise this issue - I'm just going to hijack this thread...)  

@wridgers Yes you are right. We could merge AMA + rules + about into a extendscript.github.io page. I would keep the changelog as a separate thingy for now. Maybe when its done it can be merged into the pages as well. As a working document it should stay in its own repo for now.
